version: "2"
services:
  gateway:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ${ROOT}/tmp/letsencrypt-www:/tmp/letsencrypt-www:ro
  letsencrypt:
    build:
      context: letsencrypt
      args:
        - LE_ENV=${LE_ENV}
        - EMAIL=${EMAIL}
        - CERTBOT_VERSION=0.9.1
    volumes:
      - ${ROOT}/tmp/letsencrypt-www:/tmp/letsencrypt-www
      - ${ROOT}/etc/letsencrypt:/etc/letsencrypt
    entrypoint:
      - /usr/bin/download_certs.sh
    depends_on:
      - gateway
